services:
  - type: web
    name: flask-resume-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production